#!/bin/sh -e
#
# Usage: run400 <n> ...
#       n in 1..400
#

nrJobs=`python -c 'from multiprocessing import cpu_count as n;print n()'`
export LC_ALL=C
bzipBuffer=1000000

sort=sort
if [ `uname -s` = "Darwin" ]
then
        sort=gsort # For --compress-program option
fi

expand()
{
        depth=$1
        if [ $depth -gt 1 ]
        then
                python Tools/expand.py | $sort -TTemp --compress-program=lz4 | ./combine |
                expand `expr $depth - 1`
        else
                python Tools/expand.py | BZIP2=-1 $sort -TTemp --compress-program=lbzip2 --buffer-size=$bzipBuffer | ./combine
        fi 
}

runMultiRoot()
{
        ply=$1
        /bin/echo "<runMultiRoot>,$ply,"
        expand `expr $ply - 3` |
        parallel -j $nrJobs --block 10M --pipe Tools/xmoves.sh |
        python Tools/sum.py
}

ply=$1
shift

while [ $# -gt 0 ]
do
        rootPos=`bzcat ply.2.csv.bz2 | awk -F, -v L=$1 'NR==L{print$1}'`
	echo "$rootPos,1" >&2
	echo "$rootPos,1"
        shift
done |
runMultiRoot "$ply"
